version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: sg_user
      POSTGRES_PASSWORD: sg_pass
      POSTGRES_DB: sg_db
    ports: ['5432:5432']
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: unless-stopped
    ports: ['8080:8080']
volumes:
  db_data:
